In [4]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...

In [19]:
df=pd.read_csv("IMDB Dataset.csv")
print("Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

Dataset loaded successfully!
Shape of dataset: (49396, 2)

In [26]:
# ============================================================
# 4. DISPLAY FIRST 5 REVIEWS
# ============================================================

print("\nFirst 5 rows:")
display(df.head())


# ============================================================
# 5. CHECK DATASET INFORMATION
# ============================================================

print("\nColumn names:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())


# ============================================================
# 6. REMOVE MISSING REVIEWS
# ============================================================

df = df.dropna(subset=['review'])

print("\nMissing values after removal:")
print(df.isnull().sum())


# ============================================================
# 7. CHECK DUPLICATE REVIEWS
# ============================================================

duplicates = df['review'].duplicated().sum()

print("\nNumber of duplicate reviews:", duplicates)


# ============================================================
# 8. REMOVE DUPLICATE REVIEWS
# ============================================================

df = df.drop_duplicates(subset=['review'])

print("Dataset shape after removing duplicates:", df.shape)

stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()
def clean_text(text):
    text=text.lower()
    text=re.sub(r'<.*?>','',text)
    text=re.sub(r'http\S+|www\S+','',text)
    text=re.sub(r'\d+','',text)
    text=re.sub(r'[^A-Za-z\s]','',text)
    tokens=word_tokenize(text)
    token=[word for word in tokens 
           if word not in stop_words
    ]
    tokens=[lemmatizer.lemmatize(word)for word in tokens]
    return ' '.join(tokens)
    # ============================================================
# 11. TEST THE CLEANING FUNCTION
# ============================================================

example = "This movie was AMAZING!!!"

print("\nOriginal example:")
print(example)

print("\nCleaned example:")
print(clean_text(example))


# ============================================================
# 12. APPLY CLEANING TO ALL REVIEWS
# ============================================================

print("\nCleaning all reviews...")

df['cleaned_review'] = df['review'].apply(clean_text)

print("Cleaning completed!")


# ============================================================
# 13. COMPARE ORIGINAL AND CLEANED REVIEWS
# ============================================================

print("\nOriginal vs Cleaned Reviews:")

display(
    df[['review', 'cleaned_review']].head(10)
)


# ============================================================
# 14. DISPLAY FINAL DATASET
# ============================================================

print("\nFinal dataset:")
display(df.head())


# ============================================================
# 15. CHECK FINAL COLUMNS
# ============================================================

print("\nFinal columns:")
print(df.columns.tolist())


# ============================================================
# 16. EXPORT CLEANED DATASET AS CSV
# ============================================================

output_file = "IMDB_Cleaned_Dataset.csv"

df.to_csv(output_file, index=False)

print("\nDataset exported successfully!")
print("File name:", output_file)


# ============================================================
# 17. FINAL SUMMARY
# ============================================================

print("\n========================================")
print("       PREPROCESSING COMPLETED")
print("========================================")
print("Total reviews:", len(df))
print("Columns:", df.columns.tolist())
print("Output file:", output_file)

First 5 rows:

,review,sentiment,cleaned_review
0,"$25,000 Pyramid Clues: Deep Blue Sea. Tremors....",negative,pyramid clue deep blue sea tremor slither eigh...
1,0.5/10. This movie has absolutely nothing good...,negative,this movie ha absolutely nothing good about it...
2,"0*'s Christian Slater, Tara Reid, Stephen Dorf...",negative,s christian slater tara reid stephen dorff fra...
3,"102 Dalmatians (2000, Dir. Kevin Lima) <br /><...",negative,dalmatian dir kevin lima believed to be cured ...
4,102 DALMATIANS [Walt Disney]: I wasn't a fan o...,negative,dalmatian walt disney i wasnt a fan of the pre...

Column names:
['review', 'sentiment', 'cleaned_review']

Missing values:
review            0
sentiment         0
cleaned_review    0
dtype: int64

Missing values after removal:
review            0
sentiment         0
cleaned_review    0
dtype: int64

Number of duplicate reviews: 0
Dataset shape after removing duplicates: (49396, 3)

Original example:
This movie was AMAZING!!!

Cleaned example:
this movie wa amazing

Cleaning all reviews...
Cleaning completed!

Original vs Cleaned Reviews:

,review,cleaned_review
0,"$25,000 Pyramid Clues: Deep Blue Sea. Tremors....",pyramid clue deep blue sea tremor slither eigh...
1,0.5/10. This movie has absolutely nothing good...,this movie ha absolutely nothing good about it...
2,"0*'s Christian Slater, Tara Reid, Stephen Dorf...",s christian slater tara reid stephen dorff fra...
3,"102 Dalmatians (2000, Dir. Kevin Lima) <br /><...",dalmatian dir kevin lima believed to be cured ...
4,102 DALMATIANS [Walt Disney]: I wasn't a fan o...,dalmatian walt disney i wasnt a fan of the pre...
5,1/10 and that's only because I don't go lower ...,and thats only because i dont go lower with my...
6,11:11 a.k.a. Hell's Gate (2004) is another bad...,aka hell gate is another bad horror movie that...
7,11 years after this film was released only 5 p...,year after this film wa released only people h...
8,**1/2 for this Diane Keaton farce.<br /><br />...,for this diane keaton farcesomeone should tell...
9,'1408' is the latest hodge podge of cheap scar...,is the latest hodge podge of cheap scare tacti...

Final dataset:

,review,sentiment,cleaned_review
0,"$25,000 Pyramid Clues: Deep Blue Sea. Tremors....",negative,pyramid clue deep blue sea tremor slither eigh...
1,0.5/10. This movie has absolutely nothing good...,negative,this movie ha absolutely nothing good about it...
2,"0*'s Christian Slater, Tara Reid, Stephen Dorf...",negative,s christian slater tara reid stephen dorff fra...
3,"102 Dalmatians (2000, Dir. Kevin Lima) <br /><...",negative,dalmatian dir kevin lima believed to be cured ...
4,102 DALMATIANS [Walt Disney]: I wasn't a fan o...,negative,dalmatian walt disney i wasnt a fan of the pre...

Final columns:
['review', 'sentiment', 'cleaned_review']

Dataset exported successfully!
File name: IMDB_Cleaned_Dataset.csv

========================================
       PREPROCESSING COMPLETED
========================================
Total reviews: 49396
Columns: ['review', 'sentiment', 'cleaned_review']
Output file: IMDB_Cleaned_Dataset.csv